[project]
name = "pypi-chart-badge"
version = "1.1.0"
description = "PyPI Chart Badge Generator"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kaleido==0.2.1",
    "pandas==2.2.1",
    "plotly==5.24.1",
    "pyaction==0.7.2",
    "requests==2.32.3",
]
