name: Testing

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run action
        uses: ./
        with:
          name: John
