name: Testing the action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Test:
    strategy:
      matrix:
        package: [fastapi, requests, django, boto]

    runs-on: ubuntu-latest

    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
        with:
          package_name: ${{ matrix.package }}
          file_name: ${{ matrix.package }}_badge.svg
          badge_color: '#03fc6f'
          
  Commit:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v5
