name: Testing the action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Test:
    strategy:
      matrix:
        package: [fastapi, requests, django, boto]

    runs-on: ubuntu-latest

    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
        with:
          package_name: ${{ matrix.package }}
          file_name: ${{ matrix.package }}_badge.svg
          badge_color: '#03fc6f'

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          pull: '--rebase --autostash ...'
          message: 'chart badge updated'
          
