name: Testing the action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  updating-badge-files:
    strategy:
      matrix:
        include:
          - package: fastapi
            color: blue
          - package: requests
            color: yellow
          - package: django
            color: red
          - package: boto
            color: green

    runs-on: ubuntu-latest

    name: Testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
        with:
          package_name: ${{ matrix.package }}
          file_name: ${{ matrix.package }}_badge.svg
          badge_color: ${{ matrix.color }}
          
  Commit:
    runs-on: ubuntu-latest
    needs: updating-badge-files
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Commiting
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chart badge updated'
          
