name: Testing the action

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  updating-badge-files:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - package: fastapi
            color: blue
          - package: requests
            color: yellow
          - package: django
            color: red
          - package: boto
            color: green

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run action
        uses: ./
        with:
          package_name: ${{ matrix.package }}
          file_name: ${{ matrix.package }}_badge.svg
          badge_color: ${{ matrix.color }}

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v3
        with:
          name: badge-${{ matrix.package }}
          path: .pypi_chart/${{ matrix.package }}_badge.svg

  commit-badges:
    needs: updating-badge-files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all badge artifacts
        uses: actions/download-artifact@v3
        with:
          name: '**'

      - name: Commiting
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chart badge updated'
          
